package de.thkoeln.fentwums.fsms.gui;

import java.io.File;
import javax.swing.JFileChooser;
import de.thkoeln.fentwums.fsms.logic.build.impl.MachineBuilder;
import de.thkoeln.fentwums.fsms.logHandling.LogHandler;

/**
 * Dialog to brows and select the state automaton and the input vectors.
 *
 * @author Linus Schoendorf
 */
public class LoadAutomatonDialog extends javax.swing.JDialog {

    MachineBuilder machineBuilder;
    boolean setupFlag = false;
    MainGui parent;

    JFileChooser chooser = new JFileChooser();
    private static LogHandler logHandler = LogHandler.getInstance();

    /**
     * Creates new form LoadAutomatonDialog
     * @param parent parent frame
     * @param modal specifies whether dialog blocks user input to other top-level
     *     windows when shown.
     */
    public LoadAutomatonDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.parent = (MainGui) parent;
        this.machineBuilder = this.parent.getMachineBuilder();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Text_Field_Automaton_Path = new javax.swing.JTextField();
        Button_Browse_InputVectors_Path = new javax.swing.JButton();
        Text_File_Automaton = new javax.swing.JLabel();
        Button_Browse_Automaton_Path = new javax.swing.JButton();
        Text_Field_InputVectors_Path = new javax.swing.JTextField();
        Text_File_Input_Path = new javax.swing.JLabel();
        Text_File_InputVectors = new javax.swing.JLabel();
        jButtonOK = new javax.swing.JButton();
        outputDialog = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        Text_Field_Automaton_Path.setText("*.xml");
        Text_Field_Automaton_Path.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Text_Field_Automaton_PathActionPerformed(evt);
            }
        });

        Button_Browse_InputVectors_Path.setText("Browse");
        Button_Browse_InputVectors_Path.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_Browse_InputVectors_PathActionPerformed(evt);
            }
        });

        Text_File_Automaton.setText("Automaton:");

        Button_Browse_Automaton_Path.setText("Browse");
        Button_Browse_Automaton_Path.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_Browse_Automaton_PathActionPerformed(evt);
            }
        });

        Text_Field_InputVectors_Path.setText("*.xml");
        Text_Field_InputVectors_Path.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Text_Field_InputVectors_PathActionPerformed(evt);
            }
        });

        Text_File_Input_Path.setText("Choose input file path");

        Text_File_InputVectors.setText("Input vectors:");

        jButtonOK.setText("Ok");
        jButtonOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonOK))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(outputDialog, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 76, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(Text_File_Automaton, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Text_Field_Automaton_Path, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(Text_File_InputVectors)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Text_Field_InputVectors_Path, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(82, 82, 82)
                                        .addComponent(Text_File_Input_Path, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Button_Browse_InputVectors_Path)
                    .addComponent(Button_Browse_Automaton_Path))
                .addGap(51, 51, 51))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Text_File_Input_Path, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Text_File_Automaton, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Text_Field_Automaton_Path, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_Browse_Automaton_Path))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Text_Field_InputVectors_Path, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_Browse_InputVectors_Path)
                    .addComponent(Text_File_InputVectors, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonOK)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(outputDialog, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Text_Field_Automaton_PathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Text_Field_Automaton_PathActionPerformed

        String pathName = Text_Field_Automaton_Path.getText();
        File file = new File(pathName);
        if (file.exists() && file.isFile()) {
            if (pathName.endsWith(".xml")) {
                if (!machineBuilder.setAutomatonByPath(pathName)) {
                    logHandler.addError("Automaton can not be set");
                    outputDialog.setText("Automaton can't be set!");
                } else {
                    logHandler.addMessage("Successfully selected input automaton");
                    outputDialog.setText("Successfully selected input automaton");
                    Text_Field_Automaton_Path.setText(pathName);
                }
            } else {
                logHandler.addError("Filename has to end with '.xml'");
                outputDialog.setText("Filename has to end with '.xml'");
            }
        } else {
            logHandler.addError("Selected file does not exist or is not a file");
            outputDialog.setText("Selected file does not exist or is not a file!");
        }
    }//GEN-LAST:event_Text_Field_Automaton_PathActionPerformed

    private void Button_Browse_InputVectors_PathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_Browse_InputVectors_PathActionPerformed

        int resultValue = chooser.showOpenDialog(null);
        if (resultValue == JFileChooser.APPROVE_OPTION) {
            File file = chooser.getSelectedFile();
            String pathName = file.getAbsolutePath();
            if (file.exists() && file.isFile()) {
                if (pathName.endsWith(".xml")) {
                    if (!machineBuilder.setInputVectorByPath(pathName)) {
                        logHandler.addError("Input Vectors can not be set");
                        outputDialog.setText("Input Vectors can't be set!");
                    } else {
                        logHandler.addMessage("Successfully chosen input file");
                        outputDialog.setText("Successfully chosen input file.");
                        Text_Field_InputVectors_Path.setText(pathName);
                    }
                } else {
                    logHandler.addError("Filename has to end with '.xml'");
                    outputDialog.setText("Filename has to end with '.xml'");
                }
            } else {
                logHandler.addError("Selected file does not exist or is not a file");
                outputDialog.setText("Selected file does not exist or is not a file!");
            }
        }
        setupFlag = false;
    }//GEN-LAST:event_Button_Browse_InputVectors_PathActionPerformed

    private void Button_Browse_Automaton_PathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_Browse_Automaton_PathActionPerformed

        int resultValue = chooser.showOpenDialog(null);
        if (resultValue == JFileChooser.APPROVE_OPTION) {
            File file = chooser.getSelectedFile();
            String pathName = file.getAbsolutePath();
            if (file.exists() && file.isFile()) {
                if (pathName.endsWith(".xml")) {
                    if (!machineBuilder.setAutomatonByPath(pathName)) {
                        logHandler.addError("Automaton can't be set");
                        outputDialog.setText("Automaton can't be set!");
                    } else {
                        logHandler.addMessage("Successfully selected automaton");
                        outputDialog.setText("Successfully selected input automaton");
                        Text_Field_Automaton_Path.setText(pathName);
                    }
                } else {
                    logHandler.addError("Filename has to end with '.xml'");
                    outputDialog.setText("Filename has to end with '.xml'");
                }
            } else {
                logHandler.addError("Selected file does not exist or is not a file");
                outputDialog.setText("Selected file does not exist or is not a file!");
            }
        }
        setupFlag = false;
    }//GEN-LAST:event_Button_Browse_Automaton_PathActionPerformed

    private void Text_Field_InputVectors_PathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Text_Field_InputVectors_PathActionPerformed
        String pathName = Text_Field_InputVectors_Path.getText();
        File file = new File(pathName);
        if (file.exists() && file.isFile()) {
            if (pathName.endsWith(".xml")) {
                if (!machineBuilder.setInputVectorByPath(pathName)) {
                    logHandler.addError("Input Vectors can't be set");
                    outputDialog.setText("Input Vectors can't be set!");
                } else {
                    logHandler.addMessage("Successfully selected input file");
                    outputDialog.setText("Successfully selected input file.");
                    Text_Field_InputVectors_Path.setText(pathName);
                }
            } else {
                logHandler.addError("Filename has to end with '.xml'");
                outputDialog.setText("Filename has to end with '.xml'");
            }
        } else {
            logHandler.addError("Selected file does not exist or is not a file");
            outputDialog.setText("Selected file does not exist or is not a file!");
        }
    }//GEN-LAST:event_Text_Field_InputVectors_PathActionPerformed

    private void jButtonOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOKActionPerformed

        parent.setMachineBuilder(machineBuilder);
        parent.setup();

        this.dispose();
    }//GEN-LAST:event_jButtonOKActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoadAutomatonDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoadAutomatonDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoadAutomatonDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoadAutomatonDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                LoadAutomatonDialog dialog = new LoadAutomatonDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_Browse_Automaton_Path;
    private javax.swing.JButton Button_Browse_InputVectors_Path;
    private javax.swing.JTextField Text_Field_Automaton_Path;
    private javax.swing.JTextField Text_Field_InputVectors_Path;
    private javax.swing.JLabel Text_File_Automaton;
    private javax.swing.JLabel Text_File_InputVectors;
    private javax.swing.JLabel Text_File_Input_Path;
    private javax.swing.JButton jButtonOK;
    private javax.swing.JLabel outputDialog;
    // End of variables declaration//GEN-END:variables
}
