package de.thkoeln.fentwums.fsms.gui;

import java.awt.Frame;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Hashtable;
import java.util.List;
import java.util.Vector;
import javax.swing.DefaultListModel;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;
import static javax.swing.WindowConstants.HIDE_ON_CLOSE;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.table.DefaultTableModel;
import de.thkoeln.fentwums.fsms.data.model.entities.Automaton;
import de.thkoeln.fentwums.fsms.data.model.entities.Signal;
import de.thkoeln.fentwums.fsms.data.model.entities.SignalVectorList;
import de.thkoeln.fentwums.fsms.data.model.entities.State;
import de.thkoeln.fentwums.fsms.data.model.entities.Variable;
import de.thkoeln.fentwums.fsms.logHandling.LogHandler;
import de.thkoeln.fentwums.fsms.logic.build.impl.MachineBuilder;
import de.thkoeln.fentwums.fsms.logic.simulation.impl.Simulator;

/**
 * Main GUI. Contains all important editions, buttons and options.
 *
 * @author Marvin Jolk, Linus Schoendorf
 */
public class MainGui extends javax.swing.JFrame {

    private MachineBuilder machineBuilder = new MachineBuilder();
    String automatonPath;
    private static LogHandler logHandler = LogHandler.getInstance();

    private HighlightRowRenderer renderer;

    private HighlightRowRenderer rendererInputTable;

    static LoadAutomatonDialog loadDialog;

    private DefaultTableModel tableModel;
    private HashMap<String, Integer> rowIndices;

    private DefaultTableModel tableModelInput;
    private HashMap<String, Integer> inputVectorColumnIndices;

    private DefaultTableModel tableModelVariables;
    
    /**
     * Creates new form MainGui
     */
    public MainGui() {
        initComponents();
        renderer = new HighlightRowRenderer();
        jTableOutputVector.setDefaultRenderer(Object.class, renderer);
        tableModel = new DefaultTableModel();
        jTableOutputVector.setModel(tableModel);
        jTabbedPane1.setSelectedIndex(1);
        tableModelInput = new DefaultTableModel();

        jTableInputVectors.setModel(tableModelInput);
        setTableChangedListener();
        rendererInputTable = new HighlightRowRenderer();
        jTableInputVectors.setDefaultRenderer(Object.class, rendererInputTable);

        logHandler.setjTextAreaLog(jTextAreaLog);

        tableModelVariables = new DefaultTableModel();
        tableModelVariables.addColumn("Name");
        tableModelVariables.addColumn("Identifier");
        jTableVariables.setModel(tableModelVariables);

        ResetButton.setToolTipText("Reset simulator");
        StepButton.setToolTipText("Do a single step of the simulation");
        RunSimulation.setToolTipText("Run full simulation");
        jButtonSave.setToolTipText("Save history of simulation");
        jButtonAddVector.setToolTipText("Add new vector");
        jButtonRemoveVector.setToolTipText("Remove selected vector");
        jButtonSaveInputVectors.setToolTipText("Saves the input vectors");
        
        new ImageAdministration().setLogoImageList(this);
        new ImageAdministration().setIconList(this);

    }

    public void setMachineBuilder(MachineBuilder m) {
        this.machineBuilder = m;
    }

    public MachineBuilder getMachineBuilder() {
        return this.machineBuilder;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RunSimulation = new javax.swing.JButton();
        ResetButton = new javax.swing.JButton();
        StepButton = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPaneList = new javax.swing.JScrollPane();
        jList_SimulationSteps = new javax.swing.JList<>();
        jScrollPaneTable = new javax.swing.JScrollPane();
        jTableOutputVector = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableInputVectors = new javax.swing.JTable();
        jLabelInputVectors = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaLog = new javax.swing.JTextArea();
        jButtonAddVector = new javax.swing.JButton();
        jButtonRemoveVector = new javax.swing.JButton();
        jButtonSave = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableVariables = new javax.swing.JTable();
        jLabelVariables = new javax.swing.JLabel();
        jButtonSaveInputVectors = new javax.swing.JButton();
        jMenuBar = new javax.swing.JMenuBar();
        jMenuFile = new javax.swing.JMenu();
        jMenuItemLoad = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("FSMS");

        RunSimulation.setText("Run");
        RunSimulation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RunSimulationActionPerformed(evt);
            }
        });

        ResetButton.setText("Reset");
        ResetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetButtonActionPerformed(evt);
            }
        });

        StepButton.setText("Step");
        StepButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StepButtonActionPerformed(evt);
            }
        });

        jScrollPaneList.setViewportView(jList_SimulationSteps);

        jTabbedPane1.addTab("List", jScrollPaneList);

        jTableOutputVector.setRowSelectionAllowed(false);
        jScrollPaneTable.setViewportView(jTableOutputVector);

        jTabbedPane1.addTab("Table", jScrollPaneTable);

        jTableInputVectors.setModel(new DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableInputVectors.setRowSelectionAllowed(false);
        jScrollPane1.setViewportView(jTableInputVectors);

        jLabelInputVectors.setText("Input Vectors");

        jTextAreaLog.setEditable(false);
        jTextAreaLog.setColumns(20);
        jTextAreaLog.setRows(5);
        jTextAreaLog.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextAreaLogMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTextAreaLog);

        jButtonAddVector.setText("Add");
        jButtonAddVector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddVectorActionPerformed(evt);
            }
        });

        jButtonRemoveVector.setText("Remove");
        jButtonRemoveVector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRemoveVectorActionPerformed(evt);
            }
        });

        jButtonSave.setText("Save");
        jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveActionPerformed(evt);
            }
        });

        jScrollPane3.setViewportView(jTableVariables);

        jLabelVariables.setText("Variables");

        jButtonSaveInputVectors.setText("Save");
        jButtonSaveInputVectors.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveInputVectorsActionPerformed(evt);
            }
        });

        jMenuFile.setText("Open");

        jMenuItemLoad.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemLoad.setText("Load automaton");
        jMenuItemLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemLoadActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuItemLoad);

        jMenuBar.add(jMenuFile);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonSave, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ResetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(StepButton, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(89, 89, 89)
                        .addComponent(RunSimulation, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabelInputVectors)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonAddVector)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonSaveInputVectors, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonRemoveVector, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelVariables))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ResetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(StepButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RunSimulation, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelVariables, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelInputVectors, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 506, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 514, Short.MAX_VALUE)
                            .addComponent(jScrollPane3))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonAddVector)
                            .addComponent(jButtonRemoveVector)
                            .addComponent(jButtonSave))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonSaveInputVectors)))
                .addGap(20, 20, 20))
        );

        jButtonSave.getAccessibleContext().setAccessibleDescription("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Button that starts the whole simulation.
     *
     * @param evt Activation of the button
     * @author Linus Schoendorf, Marvin Jolk
     */
    private void RunSimulationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RunSimulationActionPerformed
        resetStateList();
        if (!machineBuilder.runFullSimulation()) {
            logHandler.addError("Simulation failed");

        } else {

            logHandler.addMessage("Simulation succeeded");
            setStepList();
        }
        updateHighlightedRow();
        resetHighlightedInputVector();
        updateVariables();
    }//GEN-LAST:event_RunSimulationActionPerformed

    /**
     * Button that starts the reset of the simulation.
     *
     * @param evt Activation of the button
     * @author Linus Schoendorf, Marvin Jolk
     */
    private void ResetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetButtonActionPerformed
        machineBuilder.resetSimulator();
        resetStateList();
        logHandler.addMessage("Simulation was reset");
        updateHighlightedRow();
        highlightNextInputVector(true, 0);
        updateVariables();
    }//GEN-LAST:event_ResetButtonActionPerformed

    /**
     * Button that runs a single step of the simulation.
     *
     * @param evt Activation of the button
     * @author Linus Schoendorf, Marvin Jolk
     */
    private void StepButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StepButtonActionPerformed

        if (!machineBuilder.runSingleStep()) {
            logHandler.addError("Step failed");
        } else {
            setStepList();

            updateHighlightedRow();
            highlightNextInputVector(false, 1);
            updateVariables();
        }
    }//GEN-LAST:event_StepButtonActionPerformed

    private void jMenuItemLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemLoadActionPerformed
        //LoadAutomatonDialog loadDialog = new LoadAutomatonDialog(this, true);
        loadDialog.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        loadDialog.setLocationRelativeTo(this);
        loadDialog.setVisible(true);
    }//GEN-LAST:event_jMenuItemLoadActionPerformed

    /**
     * Adds a vector to the vector list on the selected position. If nothing is
     * selected it adds it in the end.
     *
     * @param evt Activation of the button
     * @author Linus Schoendorf, Marvin Jolk
     */
    private void jButtonAddVectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddVectorActionPerformed

        SignalVectorList s = machineBuilder.getInputVectors();
        int index = jTableInputVectors.getSelectedRow() + 1;
        if (index <= 0) {
            index = s.getSignalsVectorList().size();
        }
        if (!s.addVectorAt(index)) {
            return;
        }
        machineBuilder.setInputVectors(s);
        if (index < rendererInputTable.getHighlightedRow()) {
            updateInputVectorTable(false, 1);
        } else {
            updateInputVectorTable(false, 0);
        }
    }//GEN-LAST:event_jButtonAddVectorActionPerformed

    /**
     * Starts the ClearLog Pop-Up.
     *
     * @param evt Activation of the button
     * @author Linus Schoendorf, Marvin Jolk
     */
    private void jTextAreaLogMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextAreaLogMouseClicked
        int x = evt.getLocationOnScreen().x;
        int y = evt.getLocationOnScreen().y;
        ClearLog clearLog = new ClearLog();
        clearLog.setLocation(x, y);
        clearLog.setAlwaysOnTop(true);
        new ImageAdministration().setLogoImageList(clearLog);
        clearLog.setVisible(true);
    }//GEN-LAST:event_jTextAreaLogMouseClicked

    /**
     * Removes the selected vector.
     *
     * @param evt Activation of the button
     * @author Linus Schoendorf, Marvin Jolk
     */
    private void jButtonRemoveVectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoveVectorActionPerformed
        SignalVectorList s = machineBuilder.getInputVectors();
        int index = jTableInputVectors.getSelectedRow();
        if (!s.removeVectorAt(index)) {
            return;
        }
        machineBuilder.setInputVectors(s);
        if (index < rendererInputTable.getHighlightedRow()) {
            updateInputVectorTable(false, -1);
        } else {
            updateInputVectorTable(false, 0);
        }
    }//GEN-LAST:event_jButtonRemoveVectorActionPerformed

    /**
     * Starts the Pop-Up to save the current simulation progress and output
     * vectors.
     *
     * @param evt Activation of the button
     * @author Linus Schoendorf, Marvin Jolk
     */
    private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed
        OutputFileDialog outputDialog = new OutputFileDialog(this, true);
        outputDialog.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        outputDialog.setLocationRelativeTo(this);
        outputDialog.setVisible(true);
    }//GEN-LAST:event_jButtonSaveActionPerformed

    private void jButtonSaveInputVectorsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveInputVectorsActionPerformed
                                           
        SaveInputVectorsDialog saveInputVectorsDialog = new SaveInputVectorsDialog(this, true);
        saveInputVectorsDialog.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        saveInputVectorsDialog.setLocationRelativeTo(this);
        saveInputVectorsDialog.setVisible(true);                                    
    }//GEN-LAST:event_jButtonSaveInputVectorsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Windows look and feel 
           If the theme is not available, use default theme
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MainGui mainGui = new MainGui();
                //makes GUI Fullscreen
                mainGui.setExtendedState(Frame.MAXIMIZED_BOTH);

                mainGui.setVisible(true);
                loadDialog = new LoadAutomatonDialog(mainGui, true);
                loadDialog.setDefaultCloseOperation(HIDE_ON_CLOSE);
                loadDialog.setLocationRelativeTo(mainGui);
                loadDialog.setVisible(true);
            }
        });
    }

    /**
     * Updates the steplist textField with values from the machineBuilder.
     *
     * @author Linus Schoendorf, Marvin Jolk
     */
    private void setStepList() {
        DefaultListModel dfl = new DefaultListModel();

        List<State> stepList = machineBuilder.getCurrentSaves();
        String output;
        int stepCounter = 0;
        for (int i = 0; i < stepList.size(); i++) {
            output = "Step " + (stepCounter++ + 1) + ": " + stepList.get(i).toOutputString() + System.lineSeparator() + System.lineSeparator();
            dfl.addElement(output);
        }
        jList_SimulationSteps.setModel(dfl);
        jList_SimulationSteps.ensureIndexIsVisible(jList_SimulationSteps.getModel().getSize());
    }

    /**
     * Resets the statelist.
     *
     * @author Linus Schoendorf, Marvin Jolk
     */
    public void resetStateList() {
        jList_SimulationSteps.setModel(new DefaultListModel());
    }

    /**
     * Set the path of the automaton file.
     *
     * @param path path to set the automaton to
     * @author Linus Schoendorf, Marvin Jolk
     */
    public void setAutomatonPath(String path) {
        automatonPath = path;
    }

    /**
     * Does the setup which is needed to start the simulation.
     *
     * @return success report
     * @author Linus Schoendorf, Marvin Jolk
     */
    public boolean setup() {
        if (!machineBuilder.setupSimulation()) {
            logHandler.addError("Simulation cannot be set up");
            return false;
        }
        Simulator simulator = machineBuilder.getSimulator();
        //Set columns of output table
        tableModel = new DefaultTableModel();
        jTableOutputVector.setModel(tableModel);
        rowIndices = new HashMap<>();
        ArrayList<Signal> outputSignals = simulator.getAutomaton().getOutputSignals();
        tableModel.addColumn("State");
        for (int i = 0; i < outputSignals.size(); i++) {
            String signalName = outputSignals.get(i).getName();
            tableModel.addColumn(signalName);
        }
        //Set rows of output table
        ArrayList<State> states = simulator.getAutomaton().getStates();
        for (int i = 0; i < states.size(); i++) {
            State state = states.get(i);
            rowIndices.put(state.getName(), i);
            Hashtable outputVector = state.getOutputVector();
            Vector vector = new Vector();
            vector.add(state.getName());
            for (Signal signal : outputSignals) {
                vector.add(outputVector.get(signal));
            }
            tableModel.addRow(vector);
        }
        updateHighlightedRow();
        updateInputVectorTable(true, 0);

        //set variables
        updateVariables();
        return true;
    }

    /**
     * Updates the input vector table. Among other things required after an
     * added or removed vector.
     *
     * @param reset
     * @param increment
     * @author Linus Schoendorf, Marvin Jolk
     */
    private void updateInputVectorTable(boolean reset, int increment) {
        //Set column names of input vector table
        inputVectorColumnIndices = new HashMap<>();
        tableModelInput = new DefaultTableModel();
        SignalVectorList inputVector = machineBuilder.getInputVectors();
        ArrayList<Hashtable<String, Integer>> inputHashtable = inputVector.getSignalsVectorList();

        ArrayList<Signal> inputSignals = machineBuilder.getSimulator().getAutomaton().getInputSignals();
        for (int i = 0; i < inputSignals.size(); i++) {
            String s = inputSignals.get(i).getName();
            tableModelInput.addColumn(s);
            inputVectorColumnIndices.put(s, i);
        }
        //Set rows of input vector table
        for (int i = 0; i < inputHashtable.size(); i++) {
            Hashtable<String, Integer> h = inputHashtable.get(i);
            Vector vectorInput = new Vector();
            for (Signal signal : inputSignals) {
                vectorInput.add(h.get(signal.getName()));
            }
            tableModelInput.addRow(vectorInput);
        }
        jTableInputVectors.setModel(tableModelInput);
        setTableChangedListener();
        highlightNextInputVector(reset, increment);
    }

    /**
     * Updates the variables.
     *
     * @author Linus Schoendorf, Marvin Jolk
     */
    private void updateVariables() {
        //set variables
        tableModelVariables = new DefaultTableModel();
        tableModelVariables.addColumn("Name");
        tableModelVariables.addColumn("Value");
        jTableVariables.setModel(tableModelVariables);
        ArrayList<Variable> variables = machineBuilder.getSimulator().getAutomaton().getVariables();
        for (Variable v : variables) {
            Vector vector = new Vector();
            vector.add(v.getName());
            vector.add(v.getValue());
            tableModelVariables.addRow(vector);
        }
    }

    /**
     * Cahnges the table, to a new one.
     *
     * @author Linus Schoendorf, Marvin Jolk
     */
    private void setTableChangedListener() {
        tableModelInput.addTableModelListener(new TableModelListener() {
            @Override
            public void tableChanged(TableModelEvent e) {

                int row = e.getFirstRow();
                int column = e.getColumn();

                if (row >= jTableInputVectors.getRowCount() || jTableInputVectors.getSelectedColumn() == jTableInputVectors.getColumnCount() || row == -1 || column == -1) {
                    return;
                }

                String result = jTableInputVectors.getValueAt(row, column).toString();

                String columnName = jTableInputVectors.getColumnName(column);

                SignalVectorList inputVectors = machineBuilder.getInputVectors();
                Hashtable<String, Integer> vectorHashtable;
                try {
                    vectorHashtable = inputVectors.getVectorAt(row);
                    if (vectorHashtable == null) {
                        logHandler.addError("Vector does not exist");
                        return;
                    }
                } catch (Exception ex) {
                    logHandler.addError("Vector does not exist");
                    return;
                }

                try {
                    vectorHashtable.put(columnName, Integer.parseInt(result));
                } catch (NumberFormatException ex) {
                    logHandler.addError(result + " is not a valid signal value");
                    return;
                }
                if (!inputVectors.changeVectorAt(row, vectorHashtable)) {
                    return;
                }
                machineBuilder.setInputVectors(inputVectors);
                updateInputVectorTable(false, 0);
            }
        });
    }

    /**
     * Triggers the update of the highlighted row.
     *
     * @author Linus Schoendorf, Marvin Jolk
     */
    private void updateHighlightedRow() {
        Automaton automaton;
        if (machineBuilder.getSimulator() == null) {
            logHandler.addError("Simulator is null");
            return;
        }
        if ((automaton = machineBuilder.getSimulator().getAutomaton()) == null) {
            logHandler.addError("Automaton is null");
            return;
        }
        renderer.setHighlightedRow(rowIndices.get(automaton.getCurrentState().getName()));
        tableModel.fireTableDataChanged();
    }

    /**
     * Highlights the next input vector.
     *
     * @param reset
     * @param increment
     * @author Linus Schoendorf, Marvin JolkS
     */
    private void highlightNextInputVector(boolean reset, int increment) {
        if (reset) {
            rendererInputTable.setHighlightedRow(0);
        } else {
            rendererInputTable.setHighlightedRow(rendererInputTable.getHighlightedRow() + increment);
        }
        jTableInputVectors.scrollRectToVisible(jTableInputVectors.getCellRect(rendererInputTable.getHighlightedRow(), 0, true));
        tableModelInput.fireTableDataChanged();
    }

    /**
     * Resets the highlighted input vectors.
     *
     * @author Linus Schoendorf, Marvin Jolk
     */
    private void resetHighlightedInputVector() {
        rendererInputTable.setHighlightedRow(-1);
        jTableInputVectors.scrollRectToVisible(jTableInputVectors.getCellRect(jTableInputVectors.getRowCount() - 1, 0, true));
        tableModelInput.fireTableDataChanged();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ResetButton;
    private javax.swing.JButton RunSimulation;
    private javax.swing.JButton StepButton;
    private javax.swing.JButton jButtonAddVector;
    private javax.swing.JButton jButtonRemoveVector;
    private javax.swing.JButton jButtonSave;
    private javax.swing.JButton jButtonSaveInputVectors;
    private javax.swing.JLabel jLabelInputVectors;
    private javax.swing.JLabel jLabelVariables;
    private javax.swing.JList<String> jList_SimulationSteps;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenu jMenuFile;
    private javax.swing.JMenuItem jMenuItemLoad;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPaneList;
    private javax.swing.JScrollPane jScrollPaneTable;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTableInputVectors;
    private javax.swing.JTable jTableOutputVector;
    private javax.swing.JTable jTableVariables;
    private javax.swing.JTextArea jTextAreaLog;
    // End of variables declaration//GEN-END:variables
}
