/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package de.thkoeln.fentwums.fsms.gui;

import de.thkoeln.fentwums.fsms.data.datalogic.impl.SaveInputVectors;
import de.thkoeln.fentwums.fsms.data.datalogic.impl.TransitionHistory;
import de.thkoeln.fentwums.fsms.logHandling.LogHandler;
import de.thkoeln.fentwums.fsms.logic.build.impl.MachineBuilder;
import java.io.IOException;
import javax.swing.JFileChooser;

/**
 * Dialog to browse for the location and select the name of the save input
 * vector file and saves it.
 *
 * @author Linus Schoendorf, Marvin Jolk
 */
public class SaveInputVectorsDialog extends javax.swing.JDialog {

    MainGui parent;
    MachineBuilder machineBuilder;
    private String pathToSave;

    JFileChooser chooser = new JFileChooser();
    private static LogHandler logHandler = LogHandler.getInstance();

    /**
     * Creates new form OutputFileDialog
     *
     * @param parent parent frame
     * @param modal specifies whether dialog blocks user input to other
     * top-level windows when shown.
     */
    public SaveInputVectorsDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.parent = (MainGui) parent;
        this.machineBuilder = this.parent.getMachineBuilder();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabelOutput = new javax.swing.JLabel();
        Button_Browse_Output_PathAction = new javax.swing.JButton();
        Text_Field_Output_Path = new javax.swing.JTextField();
        outputTextField_OutputFile = new javax.swing.JLabel();
        jButtonOk = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabelOutput.setText("Outputfile for input vectors path:");

        Button_Browse_Output_PathAction.setText("Browse");
        Button_Browse_Output_PathAction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_Browse_Output_PathActionActionPerformed(evt);
            }
        });

        Text_Field_Output_Path.setEditable(false);

        jButtonOk.setText("Ok");
        jButtonOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(outputTextField_OutputFile, javax.swing.GroupLayout.PREFERRED_SIZE, 509, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(22, 22, 22)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jButtonOk)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jLabelOutput)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(Text_Field_Output_Path, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(42, 42, 42)
                                                .addComponent(Button_Browse_Output_PathAction)))
                                .addContainerGap(126, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabelOutput)
                                        .addComponent(Text_Field_Output_Path, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Button_Browse_Output_PathAction))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonOk)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(outputTextField_OutputFile, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );

        pack();
    }// </editor-fold>                        

    /**
     * Select or create the file to save the output.
     *
     * @param evt Activation of the button
     * @author Linus Schoendorf, Marvin Jolk
     */
    private void Button_Browse_Output_PathActionActionPerformed(java.awt.event.ActionEvent evt) {
        int resultValue = chooser.showOpenDialog(null);
        if (resultValue == JFileChooser.APPROVE_OPTION) {
            try {
                String pathName = chooser.getSelectedFile().getCanonicalPath();
                if (/*!pathName.endsWith(".xml") || */!pathName.endsWith(".xml")) {
                    pathName = pathName + ".xml";
                }
                pathToSave = pathName;
                Text_Field_Output_Path.setText(pathName);
                logHandler.addMessage("Successfully chosen output File for input vectors");
                outputTextField_OutputFile.setText("Successfully chosen output File for input vectors");
            } catch (IOException e) {
                logHandler.addError("IOException while trying to set/create Output File for input vectors");
                outputTextField_OutputFile.setText("IOException while trying to set/create Output File for input vectors");
            }
        } else {
            logHandler.addError("Output File for input vectors could not be set");
            outputTextField_OutputFile.setText("Output File for input vectors could not be set!");
        }

    }

    /**
     * Saves the Output.
     *
     * @param evt Activation of the button
     * @author Marvin Jolk
     */
    private void jButtonOkActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            if (SaveInputVectors.saveInputVectors(machineBuilder.getInputVectors(),pathToSave) == false) {
                logHandler.addWarning("Save input vectorsfailed");
            }
        } catch (Exception e) {
            logHandler.addWarning("Save input vectors failed");
        }
        parent.setMachineBuilder(machineBuilder);
        this.dispose();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OutputFileDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OutputFileDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OutputFileDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OutputFileDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                OutputFileDialog dialog = new OutputFileDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton Button_Browse_Output_PathAction;
    private javax.swing.JTextField Text_Field_Output_Path;
    private javax.swing.JButton jButtonOk;
    private javax.swing.JLabel jLabelOutput;
    private javax.swing.JLabel outputTextField_OutputFile;
    // End of variables declaration                   
}
