name: Java CI with Maven

on:
  push:
    branches: [ "main" ]  
    tags: [ "v*" ]        
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 25
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'temurin'
          cache: maven
          cache-dependency-path: |
            fentwums-fsm/pom.xml

      - name: Build with Maven
        run: mvn -f fentwums-fsm/pom.xml clean install

      - name: Create staging directory
        run: mkdir -p staging_dir

      - name: Move assets to staging directory
        run: cp fentwums-fsm/target/*.jar staging_dir/

      - name: Create tar
        run: |
          NAME="fentwums-fsm-${{ github.ref_name }}"
          tar -czf ${NAME}.tar.gz -C staging_dir .
          
      - name: Release artifact
        if: startsWith(github.ref, 'refs/tags/')
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: True
          replacesArtifacts: false
          generateReleaseNotes: true
          artifacts: "*.tar.gz,staging_dir/*.jar"
          omitBodyDuringUpdate: true
